### ISSUE TITLE
fix logging

### ISSUE THREAD

**Issue by elmiomar** [multiverse-nms/ndn-dpdk-agent#7]
Use Log4J or SLF4J/Logback instead of JUL.

By default Vertx uses JUL (Java-Util-Logging). I don't know if it's a bug or misconfiguration, vertx default logger only displays logs with level=info. I tried changing logger to SLF4J and it worked.

**Comment by Pesa** [comment]
@AsmaaHailane @amar-ox is this still an issue in the current code? if so, should we fix it?

**Comment by amar-ox** [comment]
I think it's fixed. [See](https://github.com/multiverse-nms/ndn-dpdk-agent/blob/9435c71ef9420ac822cc0c0c7188ed5855185406/src/main/java/nms/MainVerticle.java#L21)
