### ISSUE TITLE
compare two configuration objects

### ISSUE THREAD

**Issue by elmiomar** [multiverse-nms/ndn-dpdk-agent#8]
After retrieving the new configuration from the controller, the agent should compare it with the running configuration.

**Comment by yoursunny** [comment]
This feature is ill-defined.

For **faces**, the comparison should occur in the *face table*.
Upon receiving candidate config, a new instance of *face table* is created, and compared to the previous instance.

```go

type Face struct {
	CtrlID  string      // controller side face ID
	FwID    string      // forwarder side face ID
	Locator interface{} // address information
}

type FaceVerb int

const (
	FaceCreate FaceVerb = iota
	FaceDestroy
)

// FaceCommand represents a command to modify a face in the forwarder.
// It will set or clear FwID field after completion.
type FaceCommand struct {
	Verb FaceVerb
	Face *Face
}

type FaceTable interface {
	// Active returns a list of active faces.
	// A face is active if its FwID is non-empty.
	Active() []*Face

	// Diff generates a sequence of commands to bring the faces in the forwarder up-to-date with the configuration.
	Diff(prev FaceTable) []FaceCommand
}
```

For **routes**, the existing FIB diff algorithm should be sufficient. You don't need comparison elsewhere.

1. Delete all routes in the current RIB that have an origin within controller's range.
2. Insert routes from candidate config to the RIB.
3. Derive FIB from RIB.
4. Use FIB diff algorithm to generate FIB update commands.

**Comment by Pesa** [comment]
> This feature is ill-defined.

You haven't actually said _why_.

**Comment by yoursunny** [comment]
The proposed comparison is in the wrong place that duplicates logic.
I explained to Asmaa on conference call.

**Comment by elmiomar** [comment]
When the agent retrieves a candidate config, it compares it with the running one and applies the outcome to the forwarder.
The first config, is just a special case, and will be the same for both candidate and running. (first time candidate = running)

For the subsequent configurations, we decided to store the running config within the agent since there is no way to retrieve the list of routes from the forwarder, and we can only retrieve the list of faces. And another reason is that the faces will also have an ID assigned by the controller, not just the one assigned by the forwarder.

So, as far as I understand, for **the first configuration**, we will apply the whole candidate config, The flow will be split in two:
- the list of routes will be sent to the RIB verticle. This will result in the regular rib/fib updates.
- the list of faces will be sent to the fwd verticle. This will result in the creation of new faces on the forwarder. The IDs of the faces will be returned to be added to the running configuration object within the agent.

So, for subsequent configurations, is there any way the running config could change other than updates from the controller? Should the agent be retrieving the list faces periodically from the forwarder? or events will be sent from the forwarder whenever there is a change?
Same thing for routes, should we expect routes in running config to change? and how so?

**Comment by yoursunny** [comment]
> So, for subsequent configurations, is there any way the running config could change other than updates from the controller? Should the agent be retrieving the list faces periodically from the forwarder? or events will be sent from the forwarder whenever there is a change?
> Same thing for routes, should we expect routes in running config to change? and how so?

Faces and routes can come from these sources:

* Multiverse Controller.
* CLI tool, via the [agent API](https://github.com/elmiomar/nms-agent/blob/9eaaa331549eceb1dda81782ce00a7e5e4372da8/schema/api-description.json).
* Applications, via a mechanism to be defined in #5 (it could be a variation of agent API).

The question is, what does *running config* mean?

* Does it include only faces and routes prescribed by the controller and successfully created in the forwarder?
* Does it also cover faces and routes from other sources?
  * Why does the controller need to know these?
  * What's the ID assigned to these objects?

**Comment by elmiomar** [comment]
> The question is, what does *running config* mean?

My understanding is that the running config is an image of the config on the forwarder. So changes to the forwarder from other sources should trigger a running config update on the agent as well, that will eventually be [sent to the controller](https://github.com/amar-ox/nms-microservice/blob/master/docs/openapi/controller-to-agent.yaml#L177). This way, when the agent retrieves a new candidate config it compares it with an *accurate* running config.

> Why does the controller need to know these?

Isn't this similar to asking: why does the controller need to know about the running config?

> What's the ID assigned to these objects?

No idea. We could implement something similar to the CtrlID, however there is a risk these could overlap with the IDs assigned by the controller. I am not sure if this makes any sense, but another way is to ask the controller for an ID.

**Comment by Pesa** [comment]
This was implemented some time ago.
